/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * coffee-be
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiDocument } from './apiDocument';



export interface ApiResponsibilityFarmerPicture { 
    /**
     * description of this picture
     */
    description?: string;
    document?: ApiDocument;
}

/**
 * Namespace for property- and property-value-enumerations of ApiResponsibilityFarmerPicture.
 */
export namespace ApiResponsibilityFarmerPicture {
    /**
     * All properties of ApiResponsibilityFarmerPicture.
     */
    export enum Properties {
        /**
         * description of this picture
         */
        description = 'description',
        document = 'document'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiResponsibilityFarmerPicture',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'description',
                    classname: 'ApiResponsibilityFarmerPicture',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiDocument.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'document',
                    classname: 'ApiResponsibilityFarmerPicture',
                    dataType: 'ApiDocument',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiDocument'
                },
            ],
            validators: {
                description: [
                ],
                document: [
                ],
            }
        }
    }

  // export const ApiResponsibilityFarmerPictureValidationScheme = {
  //     validators: [],
  //     fields: {
  //               description: {
  //                   validators: []
  //               },
  //               document: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiResponsibilityFarmerPicture>;


}


