/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * coffee-be
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { WeightedAggregateAny } from './weightedAggregateAny';



export interface QuoteRequirementConfirmation { 
    fieldId?: string;
    fieldIds?: Array<string>;
    fairness?: boolean;
    provenance?: boolean;
    quality?: boolean;
    targetValue?: { [key: string]: any; };
    aggregates: Array<WeightedAggregateAny>;
}

/**
 * Namespace for property- and property-value-enumerations of QuoteRequirementConfirmation.
 */
export namespace QuoteRequirementConfirmation {
    /**
     * All properties of QuoteRequirementConfirmation.
     */
    export enum Properties {
        fieldId = 'fieldId',
        fieldIds = 'fieldIds',
        fairness = 'fairness',
        provenance = 'provenance',
        quality = 'quality',
        targetValue = 'targetValue',
        aggregates = 'aggregates'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'QuoteRequirementConfirmation',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'fieldId',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'fieldIds',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: 'Array&lt;string&gt;',
                    isPrimitiveType: true,
                    isListContainer: true,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'fairness',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'provenance',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'quality',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'targetValue',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: '{ [key: string]: any; }',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: WeightedAggregateAny.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: true,
                    name: 'aggregates',
                    classname: 'QuoteRequirementConfirmation',
                    dataType: 'Array&lt;WeightedAggregateAny&gt;',
                    isPrimitiveType: false,
                    isListContainer: true,
                    complexType: 'WeightedAggregateAny'
                },
            ],
            validators: {
                fieldId: [
                ],
                fieldIds: [
                ],
                fairness: [
                ],
                provenance: [
                ],
                quality: [
                ],
                targetValue: [
                ],
                aggregates: [
                        ['required'],
                ],
            }
        }
    }

  // export const QuoteRequirementConfirmationValidationScheme = {
  //     validators: [],
  //     fields: {
  //               fieldId: {
  //                   validators: []
  //               },
  //               fieldIds: {
  //                   validators: []
  //               },
  //               fairness: {
  //                   validators: []
  //               },
  //               provenance: {
  //                   validators: []
  //               },
  //               quality: {
  //                   validators: []
  //               },
  //               targetValue: {
  //                   validators: []
  //               },
  //               aggregates: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<QuoteRequirementConfirmation>;


}


