/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * Abelium INATrace Services API swagger documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */





export interface ApiActionType { 
    /**
     * code
     */
    code?: string;
    /**
     * Entity id
     */
    id?: number;
    /**
     * label
     */
    label?: string;
}

/**
 * Namespace for property- and property-value-enumerations of ApiActionType.
 */
export namespace ApiActionType {
    /**
     * All properties of ApiActionType.
     */
    export enum Properties {
        /**
         * code
         */
        code = 'code',
        /**
         * Entity id
         */
        id = 'id',
        /**
         * label
         */
        label = 'label'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiActionType',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'code',
                    classname: 'ApiActionType',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiActionType',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'label',
                    classname: 'ApiActionType',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                code: [
                ],
                id: [
                ],
                label: [
                ],
            }
        }
    }

  // export const ApiActionTypeValidationScheme = {
  //     validators: [],
  //     fields: {
  //               code: {
  //                   validators: []
  //               },
  //               id: {
  //                   validators: []
  //               },
  //               label: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiActionType>;


}


