/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiProductLabelFieldValue } from './apiProductLabelFieldValue';



export interface ApiProductLabelUpdateValues { 
    /**
     * Entity id
     */
    id?: number;
    /**
     * Product id
     */
    productId?: number;
    /**
     * Product label status
     */
    status?: ApiProductLabelUpdateValues.StatusEnum;
    /**
     * Product label uuid (for url)
     */
    uuid?: string;
    /**
     * label title
     */
    title?: string;
    /**
     * Label language
     */
    language?: ApiProductLabelUpdateValues.LanguageEnum;
    /**
     * Fields
     */
    fields: Array<ApiProductLabelFieldValue>;
}

/**
 * Namespace for property- and property-value-enumerations of ApiProductLabelUpdateValues.
 */
export namespace ApiProductLabelUpdateValues {
    /**
     * All properties of ApiProductLabelUpdateValues.
     */
    export enum Properties {
        /**
         * Entity id
         */
        id = 'id',
        /**
         * Product id
         */
        productId = 'productId',
        /**
         * Product label status
         */
        status = 'status',
        /**
         * Product label uuid (for url)
         */
        uuid = 'uuid',
        /**
         * label title
         */
        title = 'title',
        /**
         * Label language
         */
        language = 'language',
        /**
         * Fields
         */
        fields = 'fields'
    }

    /**
     * All possible values of status.
     */
    export enum StatusEnum {
        UNPUBLISHED = 'UNPUBLISHED',
        PUBLISHED = 'PUBLISHED'
    }

    /**
     * All possible values of language.
     */
    export enum LanguageEnum {
        EN = 'EN',
        DE = 'DE',
        RW = 'RW',
        ES = 'ES'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiProductLabelUpdateValues',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'productId',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiProductLabelUpdateValues.StatusEnum',
                    required: false,
                    name: 'status',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'uuid',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'title',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiProductLabelUpdateValues.LanguageEnum',
                    required: false,
                    name: 'language',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiProductLabelFieldValue.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: true,
                    name: 'fields',
                    classname: 'ApiProductLabelUpdateValues',
                    dataType: 'Array&lt;ApiProductLabelFieldValue&gt;',
                    isPrimitiveType: false,
                    isListContainer: true,
                    complexType: 'ApiProductLabelFieldValue'
                },
            ],
            validators: {
                id: [
                ],
                productId: [
                ],
                status: [
                ],
                uuid: [
                ],
                title: [
                        ['minlength', 0],
                        ['maxlength', 255],
                ],
                language: [
                ],
                fields: [
                        ['required'],
                ],
            }
        }
    }

  // export const ApiProductLabelUpdateValuesValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               productId: {
  //                   validators: []
  //               },
  //               status: {
  //                   validators: []
  //               },
  //               uuid: {
  //                   validators: []
  //               },
  //               title: {
  //                   validators: []
  //               },
  //               language: {
  //                   validators: []
  //               },
  //               fields: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiProductLabelUpdateValues>;


}


