/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */





export interface ApiProcessingPerformanceTotalItem { 
    unit?: string;
    year?: number;
    inputQuantity?: number;
    outputQuantity?: number;
    ratio?: number;
}

/**
 * Namespace for property- and property-value-enumerations of ApiProcessingPerformanceTotalItem.
 */
export namespace ApiProcessingPerformanceTotalItem {
    /**
     * All properties of ApiProcessingPerformanceTotalItem.
     */
    export enum Properties {
        unit = 'unit',
        year = 'year',
        inputQuantity = 'inputQuantity',
        outputQuantity = 'outputQuantity',
        ratio = 'ratio'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiProcessingPerformanceTotalItem',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'unit',
                    classname: 'ApiProcessingPerformanceTotalItem',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'year',
                    classname: 'ApiProcessingPerformanceTotalItem',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'inputQuantity',
                    classname: 'ApiProcessingPerformanceTotalItem',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'outputQuantity',
                    classname: 'ApiProcessingPerformanceTotalItem',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'ratio',
                    classname: 'ApiProcessingPerformanceTotalItem',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                unit: [
                ],
                year: [
                ],
                inputQuantity: [
                ],
                outputQuantity: [
                ],
                ratio: [
                ],
            }
        }
    }

  // export const ApiProcessingPerformanceTotalItemValidationScheme = {
  //     validators: [],
  //     fields: {
  //               unit: {
  //                   validators: []
  //               },
  //               year: {
  //                   validators: []
  //               },
  //               inputQuantity: {
  //                   validators: []
  //               },
  //               outputQuantity: {
  //                   validators: []
  //               },
  //               ratio: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiProcessingPerformanceTotalItem>;


}


