/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */





export interface ApiProductLabelFeedback { 
    /**
     * Entity id
     */
    id?: number;
    /**
     * Label id
     */
    labelId?: number;
    /**
     * Feedback type
     */
    type?: ApiProductLabelFeedback.TypeEnum;
    /**
     * Email
     */
    email?: string;
    /**
     * feedback text
     */
    feedback?: string;
    /**
     * GDPR consent
     */
    gdprConsent?: boolean;
    /**
     * Privacy policy consent
     */
    privacyPolicyConsent?: boolean;
    /**
     * Terms of use consent
     */
    termsOfUseConsent?: boolean;
    /**
     * questionnaire answers - key-answer map
     */
    questionnaireAnswers?: { [key: string]: string; };
    /**
     * The product name of label for which the feedback was provided
     */
    productName?: string;
}

/**
 * Namespace for property- and property-value-enumerations of ApiProductLabelFeedback.
 */
export namespace ApiProductLabelFeedback {
    /**
     * All properties of ApiProductLabelFeedback.
     */
    export enum Properties {
        /**
         * Entity id
         */
        id = 'id',
        /**
         * Label id
         */
        labelId = 'labelId',
        /**
         * Feedback type
         */
        type = 'type',
        /**
         * Email
         */
        email = 'email',
        /**
         * feedback text
         */
        feedback = 'feedback',
        /**
         * GDPR consent
         */
        gdprConsent = 'gdprConsent',
        /**
         * Privacy policy consent
         */
        privacyPolicyConsent = 'privacyPolicyConsent',
        /**
         * Terms of use consent
         */
        termsOfUseConsent = 'termsOfUseConsent',
        /**
         * questionnaire answers - key-answer map
         */
        questionnaireAnswers = 'questionnaireAnswers',
        /**
         * The product name of label for which the feedback was provided
         */
        productName = 'productName'
    }

    /**
     * All possible values of type.
     */
    export enum TypeEnum {
        PRAISE = 'PRAISE',
        PROPOSAL = 'PROPOSAL',
        COMPLAINT = 'COMPLAINT'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiProductLabelFeedback',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'labelId',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiProductLabelFeedback.TypeEnum',
                    required: false,
                    name: 'type',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'email',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'feedback',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'gdprConsent',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'privacyPolicyConsent',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'termsOfUseConsent',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'questionnaireAnswers',
                    classname: 'ApiProductLabelFeedback',
                    dataType: '{ [key: string]: string; }',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'productName',
                    classname: 'ApiProductLabelFeedback',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                id: [
                ],
                labelId: [
                ],
                type: [
                ],
                email: [
                        ['minlength', 0],
                        ['maxlength', 255],
                ],
                feedback: [
                        ['minlength', 0],
                        ['maxlength', 2000],
                ],
                gdprConsent: [
                ],
                privacyPolicyConsent: [
                ],
                termsOfUseConsent: [
                ],
                questionnaireAnswers: [
                ],
                productName: [
                ],
            }
        }
    }

  // export const ApiProductLabelFeedbackValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               labelId: {
  //                   validators: []
  //               },
  //               type: {
  //                   validators: []
  //               },
  //               email: {
  //                   validators: []
  //               },
  //               feedback: {
  //                   validators: []
  //               },
  //               gdprConsent: {
  //                   validators: []
  //               },
  //               privacyPolicyConsent: {
  //                   validators: []
  //               },
  //               termsOfUseConsent: {
  //                   validators: []
  //               },
  //               questionnaireAnswers: {
  //                   validators: []
  //               },
  //               productName: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiProductLabelFeedback>;


}


