/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * Abelium INATrace Services API swagger documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiCompanyBase } from './apiCompanyBase';
import { ApiCompanyCustomer } from './apiCompanyCustomer';
import { ApiDocument } from './apiDocument';
import { ApiStockOrder } from './apiStockOrder';
import { ApiUser } from './apiUser';
import { ApiUserCustomer } from './apiUserCustomer';



export interface ApiPayment {
    /**
     * Payment amount paid to the collector
     */
    amountPaidToTheCollector?: number;
    /**
     * Payment amount paid to the farmer
     */
    amountPaidToTheFarmer?: number;
    /**
     * Payment created by user
     */
    createdBy?: number;
    /**
     * Payment's currency
     */
    currency?: string;
    /**
     * Entity id
     */
    id?: number;
    /**
     * Payment time confirmation
     */
    paymentConfirmedAtTime?: Date;
    paymentConfirmedByUser?: ApiUser;
    paymentPurporseType?: ApiPayment.PaymentPurporseTypeEnum;
    /**
     * Payment purpose type
     */
    paymentPurposeType?: ApiPayment.PaymentPurposeTypeEnum;
    /**
     * Payment status
     */
    paymentStatus?: ApiPayment.PaymentStatusEnum;
    /**
     * Payment type
     */
    paymentType?: ApiPayment.PaymentTypeEnum;
    /**
     * Preferred way of payment
     */
    preferredWayOfPayment?: ApiPayment.PreferredWayOfPaymentEnum;
    /**
     * Production date
     */
    productionDate?: Date;
    /**
     * Quantity purchased to be paid
     */
    purchased?: number;
    receiptDocument?: ApiDocument;
    /**
     * Receipt document type
     */
    receiptDocumentType?: ApiPayment.ReceiptDocumentTypeEnum;
    /**
     * Receipt number
     */
    receiptNumber?: number;
    recipientCompany?: ApiCompanyBase;
    recipientCompanyCustomer?: ApiCompanyCustomer;
    /**
     * Recipient type
     */
    recipientType?: ApiPayment.RecipientTypeEnum;
    representativeOfRecipientCompany?: ApiCompanyBase;
    representativeOfRecipientUserCustomer?: ApiUserCustomer;
    stockOrder?: ApiStockOrder;
    /**
     * Payment total amount
     */
    totalPaid?: number;
    /**
     * Payment updated by user
     */
    updatedBy?: number;
}

/**
 * Namespace for property- and property-value-enumerations of ApiPayment.
 */
export namespace ApiPayment {
    /**
     * All properties of ApiPayment.
     */
    export enum Properties {
        /**
         * Payment amount paid to the collector
         */
        amountPaidToTheCollector = 'amountPaidToTheCollector',
        /**
         * Payment amount paid to the farmer
         */
        amountPaidToTheFarmer = 'amountPaidToTheFarmer',
        /**
         * Payment created by user
         */
        createdBy = 'createdBy',
        /**
         * Payment's currency
         */
        currency = 'currency',
        /**
         * Entity id
         */
        id = 'id',
        /**
         * Payment time confirmation
         */
        paymentConfirmedAtTime = 'paymentConfirmedAtTime',
        paymentConfirmedByUser = 'paymentConfirmedByUser',
        paymentPurporseType = 'paymentPurporseType',
        /**
         * Payment purpose type
         */
        paymentPurposeType = 'paymentPurposeType',
        /**
         * Payment status
         */
        paymentStatus = 'paymentStatus',
        /**
         * Payment type
         */
        paymentType = 'paymentType',
        /**
         * Preferred way of payment
         */
        preferredWayOfPayment = 'preferredWayOfPayment',
        /**
         * Production date
         */
        productionDate = 'productionDate',
        /**
         * Quantity purchased to be paid
         */
        purchased = 'purchased',
        receiptDocument = 'receiptDocument',
        /**
         * Receipt document type
         */
        receiptDocumentType = 'receiptDocumentType',
        /**
         * Receipt number
         */
        receiptNumber = 'receiptNumber',
        recipientCompany = 'recipientCompany',
        recipientCompanyCustomer = 'recipientCompanyCustomer',
        /**
         * Recipient type
         */
        recipientType = 'recipientType',
        representativeOfRecipientCompany = 'representativeOfRecipientCompany',
        representativeOfRecipientUserCustomer = 'representativeOfRecipientUserCustomer',
        stockOrder = 'stockOrder',
        /**
         * Payment total amount
         */
        totalPaid = 'totalPaid',
        /**
         * Payment updated by user
         */
        updatedBy = 'updatedBy'
    }

    /**
     * All possible values of paymentPurporseType.
     */
    export enum PaymentPurporseTypeEnum {
        ADVANCEPAYMENT = 'ADVANCE_PAYMENT',
        FIRSTINSTALLMENT = 'FIRST_INSTALLMENT',
        SECONDINSTALLMENT = 'SECOND_INSTALLMENT',
        WOMENPREMIUM = 'WOMEN_PREMIUM',
        INVOICEPAYMENT = 'INVOICE_PAYMENT'
    }

    /**
     * All possible values of paymentPurposeType.
     */
    export enum PaymentPurposeTypeEnum {
        ADVANCEPAYMENT = 'ADVANCE_PAYMENT',
        FIRSTINSTALLMENT = 'FIRST_INSTALLMENT',
        SECONDINSTALLMENT = 'SECOND_INSTALLMENT',
        WOMENPREMIUM = 'WOMEN_PREMIUM',
        INVOICEPAYMENT = 'INVOICE_PAYMENT'
    }

    /**
     * All possible values of paymentStatus.
     */
    export enum PaymentStatusEnum {
        UNCONFIRMED = 'UNCONFIRMED',
        CONFIRMED = 'CONFIRMED'
    }

    /**
     * All possible values of paymentType.
     */
    export enum PaymentTypeEnum {
        CASH = 'CASH',
        BANK = 'BANK'
    }

    /**
     * All possible values of preferredWayOfPayment.
     */
    export enum PreferredWayOfPaymentEnum {
        CASH = 'CASH',
        CASHVIACOLLECTOR = 'CASH_VIA_COLLECTOR',
        CASHVIACOOPERATIVE = 'CASH_VIA_COOPERATIVE',
        BANKTRANSFER = 'BANK_TRANSFER',
        CHEQUE = 'CHEQUE',
        OFFSETTING = 'OFFSETTING',
        UNKNOWN = 'UNKNOWN'
    }

    /**
     * All possible values of receiptDocumentType.
     */
    export enum ReceiptDocumentTypeEnum {
        PURCHASESHEET = 'PURCHASE_SHEET',
        RECEIPT = 'RECEIPT'
    }

    /**
     * All possible values of recipientType.
     */
    export enum RecipientTypeEnum {
        ORGANIZATION = 'ORGANIZATION',
        COMPANYCUSTOMER = 'COMPANY_CUSTOMER',
        USERCUSTOMER = 'USER_CUSTOMER'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiPayment',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'amountPaidToTheCollector',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'amountPaidToTheFarmer',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'createdBy',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'currency',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'paymentConfirmedAtTime',
                    classname: 'ApiPayment',
                    dataType: 'Date',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiUser.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'paymentConfirmedByUser',
                    classname: 'ApiPayment',
                    dataType: 'ApiUser',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiUser'
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.PaymentPurporseTypeEnum',
                    required: false,
                    name: 'paymentPurporseType',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.PaymentPurposeTypeEnum',
                    required: false,
                    name: 'paymentPurposeType',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.PaymentStatusEnum',
                    required: false,
                    name: 'paymentStatus',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.PaymentTypeEnum',
                    required: false,
                    name: 'paymentType',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.PreferredWayOfPaymentEnum',
                    required: false,
                    name: 'preferredWayOfPayment',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'productionDate',
                    classname: 'ApiPayment',
                    dataType: 'Date',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'purchased',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiDocument.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'receiptDocument',
                    classname: 'ApiPayment',
                    dataType: 'ApiDocument',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiDocument'
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.ReceiptDocumentTypeEnum',
                    required: false,
                    name: 'receiptDocumentType',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'receiptNumber',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiCompanyBase.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'recipientCompany',
                    classname: 'ApiPayment',
                    dataType: 'ApiCompanyBase',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiCompanyBase'
                },
                {
                    metadata: ApiCompanyCustomer.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'recipientCompanyCustomer',
                    classname: 'ApiPayment',
                    dataType: 'ApiCompanyCustomer',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiCompanyCustomer'
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiPayment.RecipientTypeEnum',
                    required: false,
                    name: 'recipientType',
                    classname: 'ApiPayment',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiCompanyBase.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'representativeOfRecipientCompany',
                    classname: 'ApiPayment',
                    dataType: 'ApiCompanyBase',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiCompanyBase'
                },
                {
                    metadata: ApiUserCustomer.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'representativeOfRecipientUserCustomer',
                    classname: 'ApiPayment',
                    dataType: 'ApiUserCustomer',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiUserCustomer'
                },
                {
                    metadata: ApiStockOrder.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'stockOrder',
                    classname: 'ApiPayment',
                    dataType: 'ApiStockOrder',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiStockOrder'
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'totalPaid',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'updatedBy',
                    classname: 'ApiPayment',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                amountPaidToTheCollector: [
                ],
                amountPaidToTheFarmer: [
                ],
                createdBy: [
                ],
                currency: [
                ],
                id: [
                ],
                paymentConfirmedAtTime: [
                ],
                paymentConfirmedByUser: [
                ],
                paymentPurporseType: [
                ],
                paymentPurposeType: [
                ],
                paymentStatus: [
                ],
                paymentType: [
                ],
                preferredWayOfPayment: [
                ],
                productionDate: [
                ],
                purchased: [
                ],
                receiptDocument: [
                ],
                receiptDocumentType: [
                ],
                receiptNumber: [
                ],
                recipientCompany: [
                ],
                recipientCompanyCustomer: [
                ],
                recipientType: [
                ],
                representativeOfRecipientCompany: [
                ],
                representativeOfRecipientUserCustomer: [
                ],
                stockOrder: [
                ],
                totalPaid: [
                ],
                updatedBy: [
                ],
            }
        }
    }

  // export const ApiPaymentValidationScheme = {
  //     validators: [],
  //     fields: {
  //               amountPaidToTheCollector: {
  //                   validators: []
  //               },
  //               amountPaidToTheFarmer: {
  //                   validators: []
  //               },
  //               createdBy: {
  //                   validators: []
  //               },
  //               currency: {
  //                   validators: []
  //               },
  //               id: {
  //                   validators: []
  //               },
  //               paymentConfirmedAtTime: {
  //                   validators: []
  //               },
  //               paymentConfirmedByUser: {
  //                   validators: []
  //               },
  //               paymentPurporseType: {
  //                   validators: []
  //               },
  //               paymentPurposeType: {
  //                   validators: []
  //               },
  //               paymentStatus: {
  //                   validators: []
  //               },
  //               paymentType: {
  //                   validators: []
  //               },
  //               preferredWayOfPayment: {
  //                   validators: []
  //               },
  //               productionDate: {
  //                   validators: []
  //               },
  //               purchased: {
  //                   validators: []
  //               },
  //               receiptDocument: {
  //                   validators: []
  //               },
  //               receiptDocumentType: {
  //                   validators: []
  //               },
  //               receiptNumber: {
  //                   validators: []
  //               },
  //               recipientCompany: {
  //                   validators: []
  //               },
  //               recipientCompanyCustomer: {
  //                   validators: []
  //               },
  //               recipientType: {
  //                   validators: []
  //               },
  //               representativeOfRecipientCompany: {
  //                   validators: []
  //               },
  //               representativeOfRecipientUserCustomer: {
  //                   validators: []
  //               },
  //               stockOrder: {
  //                   validators: []
  //               },
  //               totalPaid: {
  //                   validators: []
  //               },
  //               updatedBy: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiPayment>;


}


