/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * Abelium INATrace Services API swagger documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiProcessingOrder } from './apiProcessingOrder';
import { ApiStockOrder } from './apiStockOrder';
import { ApiStockOrderHistoryTimelineItem } from './apiStockOrderHistoryTimelineItem';



export interface ApiStockOrderHistory { 
    /**
     * Entity id
     */
    id?: number;
    processingOrder?: ApiProcessingOrder;
    stockOrder?: ApiStockOrder;
    /**
     * List of history timeline items
     */
    timelineItems?: Array<ApiStockOrderHistoryTimelineItem>;
}

/**
 * Namespace for property- and property-value-enumerations of ApiStockOrderHistory.
 */
export namespace ApiStockOrderHistory {
    /**
     * All properties of ApiStockOrderHistory.
     */
    export enum Properties {
        /**
         * Entity id
         */
        id = 'id',
        processingOrder = 'processingOrder',
        stockOrder = 'stockOrder',
        /**
         * List of history timeline items
         */
        timelineItems = 'timelineItems'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiStockOrderHistory',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiStockOrderHistory',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiProcessingOrder.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'processingOrder',
                    classname: 'ApiStockOrderHistory',
                    dataType: 'ApiProcessingOrder',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiProcessingOrder'
                },
                {
                    metadata: ApiStockOrder.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'stockOrder',
                    classname: 'ApiStockOrderHistory',
                    dataType: 'ApiStockOrder',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiStockOrder'
                },
                {
                    metadata: ApiStockOrderHistoryTimelineItem.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'timelineItems',
                    classname: 'ApiStockOrderHistory',
                    dataType: 'Array&lt;ApiStockOrderHistoryTimelineItem&gt;',
                    isPrimitiveType: false,
                    isListContainer: true,
                    complexType: 'ApiStockOrderHistoryTimelineItem'
                },
            ],
            validators: {
                id: [
                ],
                processingOrder: [
                ],
                stockOrder: [
                ],
                timelineItems: [
                ],
            }
        }
    }

  // export const ApiStockOrderHistoryValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               processingOrder: {
  //                   validators: []
  //               },
  //               stockOrder: {
  //                   validators: []
  //               },
  //               timelineItems: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiStockOrderHistory>;


}


