/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * Abelium INATrace Services API swagger documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiHistoryTimeline } from './apiHistoryTimeline';



export interface ApiStockOrderPublic { 
    historyTimeline?: ApiHistoryTimeline;
    /**
     * The global (product) order of the Stock order
     */
    orderId?: string;
    /**
     * The QR code tag
     */
    qrTag?: string;
}

/**
 * Namespace for property- and property-value-enumerations of ApiStockOrderPublic.
 */
export namespace ApiStockOrderPublic {
    /**
     * All properties of ApiStockOrderPublic.
     */
    export enum Properties {
        historyTimeline = 'historyTimeline',
        /**
         * The global (product) order of the Stock order
         */
        orderId = 'orderId',
        /**
         * The QR code tag
         */
        qrTag = 'qrTag'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiStockOrderPublic',
            vars: [
                {
                    metadata: ApiHistoryTimeline.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'historyTimeline',
                    classname: 'ApiStockOrderPublic',
                    dataType: 'ApiHistoryTimeline',
                    isPrimitiveType: false,
                    isListContainer: false,
                    complexType: 'ApiHistoryTimeline'
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'orderId',
                    classname: 'ApiStockOrderPublic',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'qrTag',
                    classname: 'ApiStockOrderPublic',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                historyTimeline: [
                ],
                orderId: [
                ],
                qrTag: [
                ],
            }
        }
    }

  // export const ApiStockOrderPublicValidationScheme = {
  //     validators: [],
  //     fields: {
  //               historyTimeline: {
  //                   validators: []
  //               },
  //               orderId: {
  //                   validators: []
  //               },
  //               qrTag: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiStockOrderPublic>;


}


